spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: rest-services
          uri: lb://rest-services
          predicates:
            - Path=/api/rest-services/**
          filters:
            - StripPrefix=2
        - id: services-auth
          uri: lb://services-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2