server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/email-password/**
        - id: aula-service
          uri: lb://aula-service
          predicates:
            - Path=/aulas/**
          filters:
            - AuthFilter
        - id: docente-service
          uri: lb://docente-service
          predicates:
            - Path=/docentes/**
          filters:
            - AuthFilter
        - id: gestion-academica-service
          uri: lb://gestion-academica-service
          predicates:
            - Path=/materias/**
          filters:
            - AuthFilter
        - id: gestion-academica-service
          uri: lb://gestion-academica-service
          predicates:
            - Path=/carreras/**
          filters:
            - AuthFilter
        - id: gestion-academica-service
          uri: lb://gestion-academica-service
          predicates:
            - Path=/planes-de-estudio/**
          filters:
            - AuthFilter
        - id: python-service
          uri: lb://python-service
          predicates:
            - Path=/python/**
          filters:
              - StripPrefix=1
