server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: seguridad-v2
          uri: https://github.com/renzo611/auta_challenge
          search-paths: config-data
  application:
    name: config-service
